version: '3.7'

services:
  # Application
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: .
      dockerfile: provision/docker/Dockerfile
    image: sheets2json-parser
    container_name: sheets2json-parser
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - public:/var/www/public:ro
      - tmp:/tmp
    networks:
      - sheets2json
  
  # Scheduler
  scheduler:
    image: sheets2json-parser
    container_name: sheets2json-parser-scheduler
    restart: unless-stopped
    working_dir: /var/www
    command: "php artisan schedule:work"
    volumes:
      - tmp:/tmp

  # Web Server
  nginx:
    image: nginx:1.17-alpine
    container_name: sheets2json-parser-nginx
    restart: unless-stopped
    ports:
      - 8882:80
    volumes:
      - public:/var/www/public:ro
      - ./provision/docker/nginx:/etc/nginx/conf.d
    networks:
      - sheets2json

# Network
networks:
  sheets2json:
    driver: bridge

# Volumes
volumes:
  public:
  tmp:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs